apiVersion: v1
kind: PersistentVolume
metadata:
  name: free-persist-volume
  labels:
    app: s-auth
spec:
  storageClassName: free-tier-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"