apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: free-persist-volume-claim
  labels:
    app: s-auth
spec:
  storageClassName: free-tier-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi