apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: free-tier-storage
  labels:
    app: s-auth
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate